### ISSUE TITLE
Is your service secure and, more importantly, is it private?

### ISSUE THREAD

**Issue by Raviu8** [meganz/MEGAchat#405]
Hi,
I am a user of mega.nz who has a pro subscription.
But I really need to be sure that your service is secure and private, with facts not claims.

So I've asked some privacy experts and they claimed against you.
I hope you can defend yourself there with facts.
https://github.com/privacytoolsIO/privacytools.io/issues/496

**Comment by megasteph** [comment]
https://mega.nz/blog_46 January 2018
**Privacy and Security**
Some cloud storage services claim to be ‘fully encrypted’ and mention encryption ‘in transit and at rest’. However, those services hold the encryption keys and can decrypt any of the user’s content, in addition to any other party who hacks the system.

MEGA decided to provide Privacy by Design rather than just Privacy by Policy. MEGA’s encryption is implemented right at the user’s device (computer, phone, tablet etc), so instead of just promising to secure the users files, it is impossible for MEGA to decrypt the content.

To enhance users’ confidence in the MEGA system, all of the client-side code is published, so interested security researchers can evaluate the encryption process. MEGA offers a vulnerability bounty and has paid out a total of EUR 15,000 for some minor vulnerabilities that were reported between 2013 and 2016. However, MEGA’s brute-force challenge, issued in February 2013, hasn’t been claimed and we are confident it never will be!

**Comment by sergiohs84** [comment]
This ticket is already too old.
Please, feel free to re-open if you want to know more about our security scheme. You might also like to have a look at https://mega.nz/SecurityWhitepaper.pdf.
Regards
