### ISSUE TITLE
Videoconference coding/bandwidth utilization performance

### ISSUE THREAD

**Issue by erotavlasme** [meganz/MEGAchat#812]
Hi,
I’m currently testing different platforms for videoconferencing. In particular, I’m comparing mega.nz, hangouts, teams and jitsi.
My setting is one sender/speaker that shares its desktop so just one video at low definition and 20-40 users audio only (muted if they do not talk).
I’m talking about bandwidth requirements: for instance [hangouts](https://support.google.com/hangouts/answer/2944865?hl=en&visit_id=637198545124000077-2837229424&rd=2) has minimum of 300 kbit/s, [teams](https://docs.microsoft.com/en-US/microsoftteams/prepare-network) has a minimum of 500 kbit/s while jitsi is close to teams.
Hangout is using [VP9](https://developers.google.com/web/updates/2016/01/vp9-webrtc), teams [h.264](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/network-requirements) codec while jitsi VP8. VP9 is comparable to h.265 and one step ahead to both VP8 and h.264.
What are the codecs used by mega.nz? Does mega.nz allow to adjust video quality (LD, SD, HD)?
Thank you

**Comment by alxvasilev** [comment]
Hi,
Unfortunately we can't compete with the "star" topologies of these services - we use a "mesh" topology, which has the benefit of p2p encryption, l but at the cost of scalability. Each participant sends their video to everybody else, so for N participants the necessary upload bandwidth is (N-1) times the bandwidth for one stream. The codecs we use are VP8 and VP9 for video and Opus for audio. The required bandwidth depends on resolution and quality - 300 or even 200 kbit/s per stream is possible. Video resolution in a group call, because of the N-1 requirement, is currently capped at 320x240, but we are working on allowing higher resolutions if network and cpu power allow it. Resolution is automatically and dynamically adjusted. There is currently no option to select the initial resolution, but it will increase automatically if the conditions allow it.

**Comment by erotavlas-turbo** [comment]
Hi,
thank you for your detailed answer. P2P is great in terms of privacy however you could consider allowing semi-centralized configuration. In particular, you could allow to one peer (the one that starts the conference) to be elected as server with routing capabilities to the other peers. In this way you could save a lot of bandwidth and increase the number of users.

**Comment by alxvasilev** [comment]
Yes, we are considering a more relaxed mode that uses the star topology. Your idea is good in theory, but in this approach call quality for everybody will greatly depend on the connection and processing power of that participant. Also, we would need to develop a dedicated application for hosting calls, because forwarding raw packets is not possible in web, and mobile devices are not practical for this. Still, it's an interesting idea and we will consider using it in some way. Thanks for your feedback!
